### ISSUE TITLE
Some error in main.py

### ISSUE THREAD

**Issue by Cayden2606** [Yariya/EarnApp-Earning-Monitor#11]
Here is a video of the issue:
https://user-images.githubusercontent.com/64778893/141776933-21b07899-8bde-441f-bccb-fe66f9a34454.mp4

the code error message:
Traceback (most recent call last):
  File "C:\Users\cayde\Desktop\Earnapp thing\EarnApp-Earning-Monitor-main\main.py", line 136, in <module>
    main()
  File "C:\Users\cayde\Desktop\Earnapp thing\EarnApp-Earning-Monitor-main\main.py", line 66, in main
    print(f"    Lifetime Balance: {x['total_earnings']}$")
KeyError: 'total_earnings'

**Comment by Yariya** [comment]
Resolved
