### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by lammersbjorn** [Yariya/EarnApp-Earning-Monitor#34]
I keep getting this error:
```
        [✓] You are on the latest version.
Traceback (most recent call last):
  File "/home/pi/EarnApp-Earning-Monitor/app/main.py", line 120, in <module>
    main()
  File "/home/pi/EarnApp-Earning-Monitor/app/main.py", line 42, in main
    info = AllInformation(config.WEBHOOK_URL, api, graphics)
  File "/home/pi/EarnApp-Earning-Monitor/app/functions.py", line 16, in __init__
    self.get_info()
  File "/home/pi/EarnApp-Earning-Monitor/app/functions.py", line 22, in get_info
    self.devices_info = self.api.get_devices_info()
  File "/home/pi/.local/lib/python3.9/site-packages/pyEarnapp/earnapp.py", line 60, in get_devices_info
    return DevicesInfo(json.loads(response.content), self.report_ip_ban)
  File "/home/pi/.local/lib/python3.9/site-packages/pyEarnapp/models/device.py", line 55, in __init__
    self.total_bandwidth_usage += device.bandwidth_usage
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
You can safely exit this
```

**Comment by Lennart01** [comment]
can confirm.
Both docker and non-docker versions are affected.

**Comment by fazalfarhan01** [comment]
Will fix it soon.
