### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by fazalfarhan01** [Yariya/EarnApp-Earning-Monitor#37]
```log
Traceback (most recent call last):
  File "/app/./main.py", line 203, in <module>
    main()
  File "/app/./main.py", line 178, in main
    webhook_templates.balance_update(info)
  File "/app/webhooks.py", line 139, in balance_update
    moneyPercentage = "{0:+.2f}%".format((info.earnings_info.balance/info.previous_balance)*100.0 - 100)
ZeroDivisionError: float division by zero
```

@Yariya I'll fix it in a while if I can.
In the meanwhile, if you are free, give it a go.

**Comment by fazalfarhan01** [comment]
added a [temporary fix](https://github.com/Yariya/EarnApp-Earning-Monitor/commit/ba6a7d439f276e0c2b9d033da298a5284997c1aa)

**Comment by fazalfarhan01** [comment]
```log
Traceback (most recent call last):
  File "/app/./main.py", line 203, in <module>
    main()
    if device_status_change[token] is not info.devices_info[token]:
  File "/app/./main.py", line 156, in main
TypeError: 'DevicesInfo' object is not subscriptable
API Version: 0.0.16.0
```

Another one

**Comment by Yariya** [comment]
Hey, sadly I had to rush the update a bit.. I'm sorry for the bugs. I will go through the code today to fix everything I see because I have more time today.. :)

**Comment by Yariya** [comment]
I've fixxed a few things

**Comment by MastaOrel** [comment]
```
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    from config import Configuration
  File "/app/config.py", line 78
    config = {
              ^
IndentationError: unindent does not match any outer indentation level
You can safely exit this
```
Another one

**Comment by Yariya** [comment]
Have you tried making an new config?

**Comment by Yariya** [comment]
Noted.

**Comment by Yariya** [comment]
fixed already pushed. releasing soon.
