### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Yariya** [Yariya/EarnApp-Earning-Monitor#39]
```Traceback (most recent call last):
  File "C:/EarnApp-Earning-Monitor/app/main.py", line 6, in <module>
    from webhooks import WebhookTemplate
  File "C:\EarnApp-Earning-Monitor\app\webhooks.py", line 5, in <module>
    from pyEarnapp.earnapp import DevicesInfo, Transaction, EarningInfo, UserData
  File "C:\EarnApp-Earning-Monitor\app\pyEarnapp\__init__.py", line 1, in <module>
    from .earnapp import EarnApp, Device, Transaction, RedeemDetails, Referee
  File "C:\EarnApp-Earning-Monitor\app\pyEarnapp\earnapp.py", line 7, in <module>
    from .models.transactions import *
  File "C:\EarnApp-Earning-Monitor\app\pyEarnapp\models\transactions.py", line 48, in <module>
    class Transactions:
  File "C:\EarnApp-Earning-Monitor\app\pyEarnapp\models\transactions.py", line 63, in Transactions
    def get_transactions(self)->list[Transaction]:
TypeError: 'type' object is not subscriptable
```

**Comment by Yariya** [comment]
pushed [bugfix](https://github.com/Yariya/EarnApp-Earning-Monitor/commit/916b4b4ebef9d961622ad4b391589f11f9de2e9c)
