### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by linax101** [Yariya/EarnApp-Earning-Monitor#40]
Suspect that the way this is being placed on a new line is breaking the setup:
https://github.com/Yariya/EarnApp-Earning-Monitor/blob/939bd667d38ccafce79ba0c1633bbaa69f7dd2b1/app/config.py#L35-L36

Causing this error
```
	[i] If you don't want to use this feature just put 0 here else put the belance that has to be exceeted here [>2.5]
Traceback (most recent call last):
  File "/app/./main.py", line 26, in <module>
    config = Configuration()
  File "/app/config.py", line 20, in __init__
    self.ask_config()
  File "/app/config.py", line 35, in ask_config
    self.AUTOMATIC_REDEEM = (input("Do you want to use automatic redeeming?\n\t[i] This helps getting your "
EOFError: EOF when reading a line
```

**Comment by linax101** [comment]
Found my problem, missing environment variable AUTOMATIC_REDEEM="0" or "1" for docker.

**Comment by fazalfarhan01** [comment]
Fixed. Updated. Pushed to dockerhub
