### ISSUE TITLE
Error when trying to start the EarnApp Monitor

### ISSUE THREAD

**Issue by AntogamerYT** [Yariya/EarnApp-Earning-Monitor#53]

**Comment by AntogamerYT** [comment]
Oops, I accidentally pressed shift+enter when trying to make the issue... haha.
Anyways, I get this error:
```
Traceback (most recent call last):
  File "/home/antogamer/EarnApp-Earning-Monitor/app/main.py", line 250, in <module>
    main()
  File "/home/antogamer/EarnApp-Earning-Monitor/app/main.py", line 71, in main
    info = AllInformation(config.WEBHOOK_URL, api, graphics)
  File "/home/antogamer/EarnApp-Earning-Monitor/app/functions.py", line 18, in __init__
    self.get_info()
  File "/home/antogamer/EarnApp-Earning-Monitor/app/functions.py", line 26, in get_info
    self.device_status = self.api.get_device_statuses()
  File "/home/antogamer/EarnApp-Earning-Monitor/app/pyEarnapp/earnapp.py", line 234, in get_device_statuses
    raise UnKnownError(
pyEarnapp.errors.UnKnownError: Failed to get device statuses. Status code: 400 Response: b'Missing CSRF token'
You can safely exit this
```
Yes, all the data is correct and I tried to remake the config more times.

**Comment by Megalaoofania** [comment]
Same issue as https://github.com/Yariya/EarnApp-Earning-Monitor/issues/50

But this is an error that most people should be getting right now.

**Comment by luisbaker** [comment]
Due to this error unusable so please do an update

**Comment by Yariya** [comment]
All issues will be resolved this week.

**Comment by Yariya** [comment]
Fixed
